// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GlobalStrategyProvider } from "@/app/choose-strategy/GlobalStrategyContext"; // ปรับเส้นทางให้ถูกต้อง
import { UserStrategyProvider } from "@/app/choose-strategy/userStrategyData";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "KOMBAT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* ครอบ Provider ทั้งหมด */}
        <UserStrategyProvider>
          <GlobalStrategyProvider>
            {children}
          </GlobalStrategyProvider>
        </UserStrategyProvider>
      </body>
    </html>
  );
}
